language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE servidor_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
