language: php

php:
  - '7.2'

before_install:
  - npm install --global cross-env
  - composer self-update
  - composer validate

install:
  - composer install --no-interaction
  - npm run dev

before_script:
  - mysql -e 'CREATE DATABASE servidor_test;'
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
