language: php

php:
  - '7.2'

before_install:
  - composer self-update

install:
  - composer install --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE servidor_test;'
  - cp .env.travis .env
